### ISSUE TITLE
Poker exercises pass on my local machine (all 30 tests), but fail online.

### ISSUE THREAD

**Issue by jameskentTX** [exercism/elixir-test-runner#101]
I'm using newest version of Elixir 1.14.3, Erlang/OTP 25

**Comment by angelikatyborska** [comment]
Hi! Sorry about the autoclosing.

Can you please copy-paste for me:
1. Your solution to the poker exercise
2. A screenshot of the test failures that you see online

**Comment by jameskentTX** [comment]
Hello Angelika. My solution is working now. I didn't know test runner is using a little different tests. And it happened that my tests were ok, but online tests failed. I had error im my code. Thank you.
