### ISSUE TITLE
Open question: What makes Elixir's test runner different from C#, Ruby, JS?

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir-test-runner#20]
There is an ongoing issue where elixir is non-performant and timing out in comparison to other languages. This thread is just a way to compile these ideas for exploration. Please edit this post to add potential issues.

Differences noticed
- Elixir docker runs as user, likw JS. Ruby/C# run as non-privileged user
- Run script exits with `1` on compile error, this is an error the more I think about it
  - [permalink](https://github.com/exercism/elixir-test-runner/blob/c3970d40d6e89b2129335f0b605c73c9caf34511/bin/run.sh#L43)

**Comment by neenjaw** [comment]
I meant to tag @ErikSchierboom and @iHiD, not assigned :P

**Comment by iHiD** [comment]
Answer: It uses networking and the others don't :)

**Comment by neenjaw** [comment]
:boom:
