### ISSUE TITLE
How to determine which version to target?

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir-test-runner#3]
How in the test runner would it work to target different versions of elixir?

The elixir track repo supports 1.6-1.9, but if we are running the test runner with any one version, solutions might fail due to library changes. 

I guess normally this would be specified in `mix.exs` but the elixir track at this point is agnostic in the solutions about which version is required -- to the point where it is commented out in `mix.exs`.

Could a version manager (like `asdf`) be put on the image then have all of the versions onboard the image then choose the appropriate version? Or is this a bigger question to even pose to the elixir track to firmly decide on a specific version to support so they the test runner is easier to maintain?

@iHiD, what is the normal for tracks in exercism?

**Comment by iHiD** [comment]
>@iHiD, what is the normal for tracks in exercism?

I think choose a version and stick to it. But as we've not deployed our first test-runner yet, we've not locked that in. I think somewhere we need to expose this to the student. Could you open an issue at https://github.com/exercism/automated-tests asking this question pls, and linking to this comment?

**Comment by neenjaw** [comment]
exercism/elixir#514 -- I think we will build and test against 1.9.2, see PR with associated github actions
