### ISSUE TITLE
Test runner spec version 3

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-test-runner#35]
There is no documentation yet.

C# is the first track to do it: https://github.com/exercism/csharp-test-runner/pull/42/files

Changes:
- `version: 3`
- each test receives a `task_id` (optional), values: an integer from 1 to N. It identifies which task the test belongs to.

Test's task id will be used to mark a task as done in the web UI if all tests for the task pass.

![image](https://user-images.githubusercontent.com/7852553/117488438-b1d83f00-af6c-11eb-9ef3-c208f2f5d5b8.png)

**Comment by ErikSchierboom** [comment]
That's quick!
