### ISSUE TITLE
"Your output" bloc not displayed when there is multiple tests 

### ISSUE THREAD

**Issue by Reunina** [exercism/elixir-test-runner#55]
for hello world exercice all is well displayed : ( when all green and when all red )
<img width="1429" alt="hello_world_tests_KO" src="https://user-images.githubusercontent.com/22769398/132097309-f3087abb-c806-40a8-86ce-cce1e6a4cbd9.png">
<img width="1416" alt="hello_worl_tests_OK" src="https://user-images.githubusercontent.com/22769398/132097312-69cfc774-3172-4a0a-9017-328dc55a45df.png">

but for exercices with multiple tests I have this :
I have the "code run" and the "test failure" parts but not the "your output" part 

<img width="1427" alt="FreeLancerRates_tests_KO" src="https://user-images.githubusercontent.com/22769398/132097303-c715e710-8641-4346-92a2-8219dc710185.png">
<img width="1427" alt="FreeLancerRates_tests_OK" src="https://user-images.githubusercontent.com/22769398/132097306-6191a26f-52aa-4918-badd-a594396a2047.png">

**Comment by jiegillet** [comment]
Thank you for opening this issue.
I tried it on the website and got the same result as you. I look at the `test_run` JSON message sent by the server and I see `"output": "hello",` in it for `hello-world`, but only `"output": null,` for `freelancer-rates`.

I added `freelancer-rates` to this repo to test it, and no output in `result.json`.
I tried it with `pythagorean-triplet` and I could see the output in `result.json` so I tried it on the website and... I timed out.

Something fishy is going on ^^

**Comment by jiegillet** [comment]
Could the difference be a concept exercise vs. practice exercise thing?

**Comment by angelikatyborska** [comment]
Works for me in: two fer, pangram
doesn't work in: protein translation

I think the difference is that it works when there are no `describe` blocks in the tests.

**Comment by jiegillet** [comment]
> I think the difference is that it works when there are no `describe` blocks in the tests.

That is some fine detective work. I will take a look as soon as I can.

**Comment by angelikatyborska** [comment]
@jiegillet's fix has been deployed and now `IO.inspect` should work in every single exercise 🎉  

Except for a few ones where the tests capture IO, that would be need for speed and rpg character sheet. I'll create an issue in the track repo to verify this and add a note if they really don't work.
