### ISSUE TITLE
Suggestion: Moving JSONFormatter to hex package 

### ISSUE THREAD

**Issue by octosteve** [exercism/elixir-test-runner#93]
Hi!

The JSONFormatter seems like it would be useful on its own. Would you be open to moving it to a hex package?

**Comment by angelikatyborska** [comment]
Hi! Thank you for the suggestion, but we're not going to do it for two reasons:
- We already have more work than we have time to do and doing this task wouldn't really improve anything on Exercism.
- The output of the JSON Formatter is dictated by Exercim's internal requirements. It could never be changed based on the package's users' needs, but it would need to unexpectedly be changed if Exercism needs it to, breaking the package's users' code. That would be a frustrating experience for everybody.

For those reasons, if somebody is really interested in reusing that code, I would recommend good old copy-paste 😉.

**Comment by octosteve** [comment]
Thanks!
